spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: b2ccc4b2aea13a0177528a9f3d9b97ce
            client-secret: 7iCyUW6VarCPsjAwQOTrYTJzeRCQ5LoA
            client-name: Kakao
            redirect-uri: http://k6c102.p.ssafy.io:8080/v1/oauth/login
#            redirect-uri: http://localhost:8081/v1/oauth/login
            scope: profile_nickname, profile_image
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
