version: '3.2'
services:
  redis-server:
    image: 'redis'
    container_name: 'porong-ranking-redis'
    ports:
      - "6380:6379"
  porong-ranking-server:
    image: 'sangjs39/porong-ranking-server' # ?
    container_name: 'porong-ranking-server'
    ports:
      - "8085:8085"
