# Spring Cloud Gateway ? ???? port ??
server:
  port: 8888

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: http://localhost:3000
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
              - AccessToken
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE

      # Spring Cloud Gateway ?? Filter
      default-filters: 
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true

      # routing microservice
      routes:

        # auth service filter
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/oauth/login/response

        # member signup service filter
        - id: member-signup-service
          uri: http://localhost:8080
          predicates:
            - Path=/member/signup
          filters:
            - name: MemberFilter
              args:
                baseMessage: Spring Cloud Gateway MemberFilter for Member SignUp
                preLogger: true
                postLogger: true

        # member service filter
        - id: message service
          uri: http://localhost:8080
          predicates:
            - Path=/member/**
          filters:
            - name: AuthFilter
              args:
                baseMessage: Spring Cloud Gateway AuthFilter for Member Service
                preLogger: true
                postLogger: true

        # message service filter
        - id: message service
          uri: http://localhost:8080
          predicates:
            - Path=/v1/message/**
          filters:
            - name: AuthFilter
              args:
                baseMessage: Spring Cloud Gateway AuthFilter for Message Service
                preLogger: true
                postLogger: true

# gateway 8888
# auth 8082
# common 8080