server:
  port: 8085

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  cache:
    type: redis
  redis:
    # host: host.docker.internal
    host: "j6c104.p.ssafy.io"
    #    host: localhost
    port: 6380