spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testdb?serverTimezone=Asia/Seoul&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: update
      ddl-auto: create
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        show_sql: true
        format_sql: true

  logging.level:
    org.hibernate.SQL: info
#    org.hibernate.type: trace