server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://k6C102.p.ssafy.io:3307/auth?serverTimezone=Asia/Seoul&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: update
      ddl-auto: create
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        show_sql: true
        format_sql: true

  logging.level:
    org.hibernate.SQL: info
#    org.hibernate.type: trace
